pub mod message_chat;
pub mod message_movement;
pub mod message_new_player;
pub mod message_make_account;
pub mod message_verify_account;
pub mod message_enter_player_to_game;
pub mod message_allow_connect;
pub mod message_server_response;
pub mod message_delete_player;